### ISSUE TITLE
Warning:: tensorFlow

### ISSUE THREAD

**Issue by chaiein** [themightyoarfish/deepVO#3]
WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/deepVO/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.

How can I solve the above issue.

**Comment by themightyoarfish** [comment]
Too little information. If you're using a newer tf version than me when I wrote this (1.7), then check where the problem comes from, then you can change the code appropriately. But for now it seems to be a warning only.
