### ISSUE TITLE
How to run the code and check the results

### ISSUE THREAD

**Issue by chaiein** [themightyoarfish/deepVO#4]
Please give the instructions to run the code
I am using pycharm, How to give the arugments.  I gave dataset path as the folder with images
usage: Train the DeepVO model [-h] -d DATASET -o
                              {Adagrad,Adam,GradientDescent,Ftrl,Momentum,Adadelta,ProximalAdagrad,ProximalGradientDescent,SyncReplicas,RMSProp,AdagradDA}
                              -l LEARNING_RATE -b BATCH_SIZE -e EPOCHS
                              [-f FLOWNET] -m MEMORY_SIZE -s SEQUENCE_LENGTH
                              [-r] [-v] [-w WIDTH] [-c]
Train the DeepVO model: error: the following arguments are required: -d/--dataset, -o/--optimizer, -l/--learning-rate, -b/--batch-size, -e/--epochs, -m/--memory-size, -s/--sequence-length

When I modified the line 
parser.add_argument('-d', '--dataset', default='/home/ubuntu/Downloads/2011_09_26/2011_09_26_drive_0001_extract/image_00' , type=str, required=True, help='data')
Still I have the same error
Please help me to solve this issue

**Comment by themightyoarfish** [comment]
Refer to the pycharm documentation on how to pass command line args. Doesn't seem like it relates to this repository.
